language: cpp
sudo: false

os:
  - linux

compiler:
  - gcc

addons:
  postgresql: "9.3"
  apt:
    sources:
    - george-edison55-precise-backports
    - llvm-toolchain-precise-3.5
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-3.5
    - flex
    - g++-4.9
    - libpq-dev
    - libpq5
    - libstdc++6
    - libtool
    - pkg-config
    - cmake-data
    - cmake
    - make

script: ./travis-build.sh

branches:
 only:
 - cmake_linux
